# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

project_name: signoz-community

before:
  hooks:
    - go mod tidy

builds:
  - id: signoz
    binary: bin/signoz
    main: ./cmd/community
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    goarm64:
      - v8.0
    ldflags:
      - -s -w
      - -X github.com/SigNoz/signoz/pkg/version.version=v{{ .Version }}
      - -X github.com/SigNoz/signoz/pkg/version.variant=community
      - -X github.com/SigNoz/signoz/pkg/version.hash={{ .ShortCommit }}
      - -X github.com/SigNoz/signoz/pkg/version.time={{ .CommitTimestamp }}
      - -X github.com/SigNoz/signoz/pkg/version.branch={{ .Branch }}
      - -X github.com/SigNoz/signoz/pkg/analytics.key=9kRrJ7oPCGPEJLF6QjMPLt5bljFhRQBr
    mod_timestamp: "{{ .CommitTimestamp }}"
    tags:
      - timetzdata

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{- .Os }}_{{- .Arch }}
    wrap_in_directory: true
    strip_binary_directory: false
    files:
      - src: README.md
        dst: README.md
      - src: LICENSE
        dst: LICENSE
      - src: frontend/build
        dst: web
      - src: conf
        dst: conf
      - src: templates
        dst: templates

release:
  name_template: "v{{ .Version }}"
  draft: false
  prerelease: auto

dockers:
  - id: signoz-community-amd64
    ids:
      - signoz
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: ./cmd/community/Dockerfile.ghcr
    build_flag_templates:
      - --platform=linux/amd64
    extra_files:
      - frontend/build
      - templates
    image_templates:
      - "ghcr.io/rezuscloud/signoz:v{{ .Version }}-community-amd64"
  - id: signoz-community-arm64
    ids:
      - signoz
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: ./cmd/community/Dockerfile.ghcr
    build_flag_templates:
      - --platform=linux/arm64
    extra_files:
      - frontend/build
      - templates
    image_templates:
      - "ghcr.io/rezuscloud/signoz:v{{ .Version }}-community-arm64"

docker_manifests:
  - id: signoz-community
    name_template: "ghcr.io/rezuscloud/signoz:v{{ .Version }}-community"
    image_templates:
      - "ghcr.io/rezuscloud/signoz:v{{ .Version }}-community-amd64"
      - "ghcr.io/rezuscloud/signoz:v{{ .Version }}-community-arm64"
